USE [master]
GO

/****** Object:  Database [DBAPerfData]    Script Date: 03/09/2019 12:23:34 ******/
CREATE DATABASE [DBAPerfData]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBAPerfData', FILENAME = N'Z:\MSSQL\Data\DBAPerfDataAXLIVE.mdf' , SIZE = 42138112KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'DBAPerfData_log', FILENAME = N'Z:\MSSQL\Data\DBAPerfDataAXLIVE.ldf' , SIZE = 3790208KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DBAPerfData] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBAPerfData].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBAPerfData] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBAPerfData] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBAPerfData] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBAPerfData] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBAPerfData] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBAPerfData] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBAPerfData] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBAPerfData] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBAPerfData] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBAPerfData] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBAPerfData] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBAPerfData] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBAPerfData] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBAPerfData] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBAPerfData] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DBAPerfData] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBAPerfData] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBAPerfData] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBAPerfData] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBAPerfData] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBAPerfData] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBAPerfData] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBAPerfData] SET RECOVERY FULL 
GO

ALTER DATABASE [DBAPerfData] SET  MULTI_USER 
GO

ALTER DATABASE [DBAPerfData] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBAPerfData] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBAPerfData] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBAPerfData] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DBAPerfData] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DBAPerfData] SET  READ_WRITE 
GO


